# By PuXiongfei

name: Build u-boot

on:
  workflow_dispatch:
    inputs:
      tags:
        description: "v<year>.<month>"
        required: true
        default: "master"

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 10240
          remove-dotnet: "true"
          remove-android: "true"
          remove-haskell: "true"

      - name: Initialization environment
        run: |
          echo "Free space:"
          df -hT
          sudo timedatectl set-timezone "$TZ"
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install gcc gcc-aarch64-linux-gnu
          sudo -E apt-get -qq install bc bison build-essential \
          device-tree-compiler dfu-util efitools flex gdisk graphviz imagemagick \
          liblz4-tool libgnutls28-dev libguestfs-tools libncurses-dev \
          libpython3-dev libsdl2-dev libssl-dev lz4 lzma lzma-alone openssl \
          pkg-config python3 python3-coverage python3-pkg-resources \
          python3-pycryptodome python3-pyelftools python3-pytest \
          python3-sphinxcontrib.apidoc python3-sphinx-rtd-theme python3-virtualenv \
          swig

      - name: Checkout self
        uses: actions/checkout@v2

      - name: Checkout u-boot repository
        uses: actions/checkout@v2
        with:
          path: u-boot
          repository: u-boot/u-boot
          ref: ${{ github.event.inputs.tags }}

      - name: Apply patch
        run: |
          cd u-boot
          cat $GITHUB_WORKSPACE/patch/phicomm-n1-u-boot.patch
          git apply $GITHUB_WORKSPACE/patch/phicomm-n1-u-boot.patch
          git diff
          echo "FILE_DATE=$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

      - name: Show .config
        run: |
          cd u-boot
          make phicomm-n1_defconfig
          cat .config

      - name: Compile u-boot
        id: compile
        run: |
          cd u-boot
          CROSS_COMPILE=aarch64-linux-gnu- make -j$(nproc)
          echo "::set-output name=status::success"

      - name: Organize files
        id: organize
        if: steps.compile.outputs.status == 'success' && !cancelled()
        run: |
          mkdir -p ${{ github.event.inputs.tags }}
          cd ${{ github.event.inputs.tags }}
          echo "UPLOAD_PATH=${PWD}" >> $GITHUB_ENV
          [[ -f ${GITHUB_WORKSPACE}/u-boot/u-boot.bin ]] && sudo cp -a ${GITHUB_WORKSPACE}/u-boot/u-boot.bin ./
          echo "::set-output name=status::success"

      - name: Upload output
        uses: actions/upload-artifact@v2
        if: steps.organize.outputs.status == 'success' && !cancelled()
        with:
          name: phicomm-n1-u-boot_${{ github.event.inputs.tags }}
          path: ${{ env.UPLOAD_PATH }}

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 1
          keep_minimum_runs: 1
